services:
  db:
    image: postgres:16
    container_name: ad-dashboard-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: addashboard
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
